# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d281829ee8ee4a68da4c117ffdd54962647866c70df0a0507fe5c455771df7c8d016c0c23f263ee6086e05b09b1f83bdc8509a8d0ab718002049e38870ea7336

test:
  secret_key_base: b773708b6f0cecfdaa71b3f8c0af16f04de1f7bd99648c409159c3d867a8d1fa846854af23340ea84af661d726db6fbbcb0cdb0a7db61a284b891b68eccacd54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
